version: '3.7'
services:
  db:
    image: postgres:16
    container_name: vseobot_db 
    env_file:
      - .env-non-dev 
    ports: 
      - 5432:5432 
     
  vseobot: 
    image: vseobot 
    build: 
      context: .
    container_name: vseobot_app
    env_file:
      - .env-non-dev
    depends_on:
      - db 
    command: ["/linwex_vseobot/docker/app.sh"]
    ports: 
      - 8000:8000
    



